# Generated by Django 5.0.4 on 2024-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='default_task_name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/<django.db.models.fields.CharField>/'),
        ),
    ]
