# Generated by Django 5.0.4 on 2024-05-23 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='session_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
