# Generated by Django 5.0.4 on 2024-05-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_useranswer_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeAnswer',
        ),
    ]
